---
resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: repository
    type: git
    source:
      uri: https://github.com/jwilm/alacritty.git
  - name: build
    type: git
    source:
      uri: https://github.com/raba-jp/pipelines.git
  - name: s3
    type: s3
    source:
      access_key_id: {{aws_access_key_id}}
      secret_access_key: {{aws_secret_access_key}}
      bucket: {{aws_bucket}}
      endpoint: {{aws_s3_endpoint}}
  - name: slack
    type: slack-notification
    source:
      url: {{slack_webhook_url}}
  - name: timer
    type: time
    source:
      start: 06:00 PM
      stop: 12:00 PM
      location: Asia/Tokyo

jobs:
  - name: test
    plan:
      - aggregate:
        - get: repository
          trigger: true
        - get: build
          trigger: true
        - get: timer
          trigger: true
      - task: test
        file: build/alacritty/tasks/test.yml
  - name: build
    plan:
      - aggregate:
        - get: repository
          trigger: true
          passed: [test]
        - get: build
          trigger: true
          passed: [test]
      - task: build
        file: build/alacritty/tasks/build.yml
      - put: s3
        params:
          file: alacritty.tar.gz
      - put: slack
        params:
          channel: '#ci'
          text: alacritty origin build complete!
