---
resource_types:
  - name: google-drive
    type: docker-image
    source:
      repository: jpatel4pivotal/google-drive-concourse-resource
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource
      tag: latest

resources:
  - name: repository
    type: git
    source:
      uri: https://github.com/jwilm/alacritty.git
  - name: build_repo
    type: git
    source:
      uri: https://github.com/raba-jp/build_alacritty.git
  - name: drive
    type: google-drive
    source:
      drive_client_email: {{google_drive_client_email}}
      drive_client_id: {{google_drive_client_id}}
      drive_private_key_id: {{google_drive_private_key_id}}
      drive_private_key: {{google_drive_private_key}}
      drive_folder_id: {{google_drive_folder_id}}
  - name: slack
    type: slack-notification
    source:
      url: {{slack_webhook_url}}
  - name: timer
    type: time
    source:
      start: 06:00 PM
      stop: 12:00 PM
      location: Asia/Tokyo

jobs:
  - name: test
    plan:
      - aggregate:
        - get: repository
          trigger: true
        - get: build_repo
          trigger: true
        - get: timer
          trigger: true
      - task: test
        file: build_repo/tasks/test.yml
  - name: build
    plan:
      - aggregate:
        - get: repository
          trigger: true
          passed: [test]
        - get: build_repo
          trigger: true
          passed: [test]
      - task: build
        file: build_repo/tasks/build.yml
      - put: drive
        params:
          file_name: repository/target/release
      - put: slack
        params:
          channel: '#ci'
          text: alacritty origin build complete!
