---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: rust
inputs:
  - name: repository
run:
  path: /bin/sh
  args:
    - -exc
    - |
      apt-get update
      apt-get install -y cmake libfreetype6-dev libfontconfig1-dev xclip
      cd repository
      rustup override set stable
      rustup update stable
      cargo build --release
