---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: rust
inputs:
  - name: repository
run:
  path: /bin/sh
  args:
    - -exc
    - |
      apt-get update
      apt-get install -y cmake
      cd repository
      cargo test --no-default-features
