---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: rabajp/build_alacritty_origin
inputs:
  - name: repository
outputs:
  - name: workspace
run:
  path: /bin/bash
  args:
    - -c
    - |
      mkdir workspace
      cd repository
      rustup override set stable
      rustup update stable
      cargo build --release
      cd ../
      cp -R ./repository/target workspace
      tar zcvf alacritty.tar.gz workspace
