---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: rabajp/build_alacritty_origin
inputs:
  - name: repository
outputs:
  - name: workspace
run:
  path: /bin/bash
  args:
    - -c
    - |
      mkdir repository/target
      cp -R /tmp/alacritty/target/release repository/target
      cd repository
      rustup override set stable
      rustup update stable
      cargo build --release --target x86_64-apple-darwin
      cd ../
      cp -R ./repository/target workspace
