---
platform: darwin
inputs:
  - name: repository
outputs:
  - name: workspace
run:
  path: /bin/bash
  args:
    - -c
    - |
      export PATH=/usr/local/bin:$PATH
      cd repository
      rustup override set stable
      rustup update stable
      cargo build --release --target x86_64-apple-darwin
      zip alacritty.zip target/release/osx/Alacritty.app
      cp alacritty.zip ../workspace
