---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: rabajp/build_alacritty_origin
inputs:
  - name: repository
run:
  path: /bin/sh
  args:
    - -exc
    - |
      cd repository
      cargo test --no-default-features --release
