---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: rabajp/build_alacritty_origin
inputs:
  - name: repository
run:
  path: /bin/sh
  args:
    - -exc
    - |
      mkdir repository/target
      cp -R /tmp/alacritty/target/debug repository/target
      cd repository
      cargo test --no-default-features --target x86_64-apple-darwin
