---
platform: darwin
inputs:
  - name: repository
run:
  path: /bin/bash
  dir: repository
  args:
    - -c
    - |
      export PATH=/usr/local/bin:$PATH
      cargo test --no-default-features --target x86_64-apple-darwin
